### ISSUE TITLE
Missing Heading Content - Homepage

### ISSUE THREAD

**Issue by c-deems** [alaoweb/2021.alaoweb.org#102]
Per the Pa11y Dashboard, an empty Heading tag is listed somewhere in the code. Not sure if we have plans for it and are just waiting on more info, but want to note it exists so we don't forget.

Link to the Homepage in Pa11y Dashboard: http://pa11y.alaoweb.org/60f09064fae3030008f1eae8

Impacted line:
`<h2 class="serviceproject h3"></h2>`

**Comment by kenirwin** [comment]
this is in `_includes/serviceproject.html`:
```
      {% if site.serviceprojectTitle %}
        <h2 class="serviceproject h3">{{ site.serviceprojectTitle }}</h2>
      {% endif %}
```

This should be resolved by #96 once the project data is defined in `_config.yml`

**Comment by kenirwin** [comment]
Assigning to @tuckerk3 -- When you build out the serviceproject.html section of the main page, please check to see that the title is rendering inside the `<h2>` tag

**Comment by kenirwin** [comment]
I take it back -- @tuckerk3, you can ignore this one. 

I'll fix this on the logic side
