### ISSUE TITLE
update Google maps API key for 2021.alaoweb.org

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#11]

**Comment by dwgreen1** [comment]
The map isn't being used anywhere right now, is it? Since we're virtual again, we can clear out the key for this year's conference, or I think when Derek set up the Google Maps API, it was for the alaoweb.org domain, so there probably isn't a need to update it in the first place, is there?

**Comment by kenirwin** [comment]
Yup - I think you're right; might be needed  next year, but that's next year's problem.
