### ISSUE TITLE
Service Project Display

### ISSUE THREAD

**Issue by tuckerk3** [alaoweb/2021.alaoweb.org#149]
Is there a way to make the service project information easier to find on the conference home page? Something similar to "register" anchor might work.

**Comment by kenirwin** [comment]
@tuckerk3 - that seems like a good idea. Do you want to give it a go? 

Buttons are defined in _config.yml under "# Call to Action Buttons"

You can uses this as the target: 
"/#serviceproject"

**Comment by tuckerk3** [comment]
@kenirwin Will do. Thanks, Ken!

**Comment by kenirwin** [comment]
closed by #151
