### ISSUE TITLE
can we have live chat during video playback, like ACRL? 

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#17]
"They showed the prerecorded presentations in an interface that allowed for real time chat. Think a Zoom meeting where the presenter is screen sharing a YouTube video. I think we vaguely spitballed showing the YouTube videos in each session's Zoom meeting last year, but decided it would be safer technology-wise to just have attendees watch at YouTube. Maybe I'm imagining that conversation... Anyway, Cara said the simultaneous chat was great, and that the presenters were able to participate. It might also take some pressure off the time allotted for Q&A. Not sure if we can make that idea happen, though."

**Comment by dwgreen1** [comment]
One option might be to look at [YouTube Premiers,](https://www.youtube.com/howyoutubeworks/product-features/live/#youtube-premieres) part of YouTube Broadcasts. One benefit is that we are leveraging YouTube all the same; one drawback is that you cannot use private YouTube videos for a broadcast. You would probably have to load each video into a separate YouTube account publicly to set up the broadcasts and then hope no one discovers them (security through obscurity).
