### ISSUE TITLE
what can we do to speed up page loads?

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#18]
Especially schedule page: 37s

**Comment by kenirwin** [comment]
The schedule page (and probably other pages like the session search and poster pages) apparently load every session video in an iframe inside a hidden modal at page load. Let's find a way to lazy-load or otherwise not call up youtube until that session is clicked. 

We've been talking about having sessions load in a new window #6 so we might look at how these two fixes could fit together.

**Comment by kenirwin** [comment]
Thanks for tackling this @dwgreen1 -- I'll be curious to see what you come up with!

**Comment by dwgreen1** [comment]
We can discuss this further, but what I found was that there is a `loading=lazy` attribute that can be added to an iframe; however, I'm not happy with it. In Safari you have to enable an Experimental Feature in order for it to work, and it does work wonderfully after you've done so. In Chrome, the feature is supposed to be supported, but I saw no difference in page load speeds like I did in Safari. Apparently their implementation is not the same as everyone else's. When I checked Firefox only supported it for images, not iframes. Edge is supposed to support it, but I did not test.

With that in mind, I think our best bet will probably be to implement a third-party JS library, maybe one of these:

- https://github.com/vb/lazyframe
- https://github.com/wingkwong/lazy-load-youtube-videos/
- https://github.com/the-muda-organization/youtube-lazyload/

...or we can write up our own. For example, on a modal open, (re)write the iframe at that time.

**Comment by kenirwin** [comment]
I was working on this last week a bit before you took the issue and I also found that lazy-loading had no discernible effect. I started working on a "on a modal open, (re)write the iframe at that time" but was unsuccessful in getting getting that event to trigger.

an event handler might be lower overhead, but if we can't get that to work, then maybe a third party solution makes sense.

**Comment by dwgreen1** [comment]
I have added the following to scripts.js:

```js
    // Lazy load modal iframes
      $('[id^="sessionDetail-"]').on("show.bs.modal", function () {
          let iframe = $(this).find('.lazyload')
          iframe.attr('src', iframe.data('src'));
      });
```

It seems to cut down the page load drastically. Could someone test with the lazy-load branch and see whether this is a satisfactory first step? Do we need to find ways to cut down the page load time even further?

**Comment by kenirwin** [comment]
That's a huge improvement! We might want to look for other possible improvements too, but I get a usable page in about 4s.

Thanks @dwgreen1

**Comment by kenirwin** [comment]
@dwgreen1 - is there any reason not to merge this branch into main now?

**Comment by dwgreen1** [comment]
@kenirwin  No. I was going to see what else I could do, but I got distracted. We should go ahead and merge this, though, because it will make everyone's life easier as we continue developing. If we want to come back to additional speed improvements later, we can.
