### ISSUE TITLE
Method to Assign Relevant IG Labels to Sessions

### ISSUE THREAD

**Issue by dzoladz** [alaoweb/2021.alaoweb.org#2]
At the moment, there is no method in place to assign IG labels to relevant conference sessions and posters. We'll need to think about how best to update the data models to handle this additional piece of information. We'll also need to consider the display of these labels in session modals, poster templates, schedule grid, schedule filters, and any other relevant features of the site were we think they would be useful.

Personally, I do not think this is something that the 2020 team need to complete. In fact, I would discourage us from taking on this enhancement. I would prefer that the 2021 team take this up and give it the consideration that it deserves, before proposing a solution that 'gets the job done', but in a way that deters or distracts from the utility of the 2020 site.

> I will not assign anyone to this issue, but if you have the time to tackle it for 2020, feel free to self-assign. **If you do self-assign, I’m going to ask that you open a pull request for the enhancement no later than the end of the day on Monday, October 19th**. If no one self-assigns, we’ll just add a 2021 label to the issue and transfer it to the 2021 repo following the conference.

**Comment by kenirwin** [comment]
#91 makes the interest group/audience info searchable, and make it show up in session descriptions (Issue #19) but so far there is no mechanism for browsing by audience group. It would be nice to have a pulldown in the session search page, but so far that has eluded me.
