### ISSUE TITLE
update hero image on the front page

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#24]
- [ ] file goes in `img/section-images/`
- [ ] defined in `_config.yml`
- [ ] also update adjacent textual metadata re: event title, dates, etc.
  - October 27-29, 2021
  - Building Bridges: Dialogue, Deliberation & Connection in Academic Libraries

**Comment by WebShivam** [comment]
I want to take this issue Can you assign me please, I'm new to Open Source and looking forward to do some contributions

A doubt!
Do I need to put hero-img "resilience_logo_white.svg" in `img/section-images/` or I need to look for hero-img in the same directory, if yes then I could not find it in the repo
