### ISSUE TITLE
Embiggen font sizes and logo

### ISSUE THREAD

**Issue by maxfieldk29** [alaoweb/2021.alaoweb.org#35]
Make the ALAO logo big enough to read what ALAO actually stands for
Increase font size of navigation menu on top and bottom

**Comment by kenirwin** [comment]
I started to work on this in the branch 'embiggen-main-logo'; it turns out that the light-text version of the logo has been cropped so that part of "Ohio" is missing. I'm working on getting a full copy to replace it.
