### ISSUE TITLE
posters to grid

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#40]
example: https://codepen.io/kenirwin/pen/GRWBNzB?editors=1000

But when I tried to do this on the site, the bootstrap "row" class was not respected. I suspect that the Bootstrap SASS may build incompletely or old or wrong version or something.

Last year we experienced some iffy bootstrap functionality; we'll need to find a fix for that.

**Comment by dwgreen1** [comment]
If I recall, it seems that only certain pieces of Bootstrap were enabled/included. We might need to take a closer look at what is actually being brought in. Having said that, I am a big fan of the cards. I think it should do the trick.

**Comment by kenirwin** [comment]
That was my first thought too -- it looks like the BS grid is included; but even when I turned on all the bootstrap and turned off all the rest of the css is didn't work. (The cards themselves work, but the "row" handling of the narrow cards did not.) I wonder if there's something wonky in our implementation of the Bootstrap includes, or maybe a mismatch between the CSS and the JS versions or something like that.
