### ISSUE TITLE
OLSSI session sponsor

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#60]
per Allen R: 
OLSSI will sponsor the session "Practicing organizational care: Using human-centered approaches to facilitate change in your library"

I don't know how to create that connection, but we can figure that out...

**Comment by tuckerk3** [comment]
Hi Ken, we will also need to add RPC sponsor for poster session "Teaching to the Same Audience: Collaboration between Instruction and Special Collections Teams". Since this is for a poster; should I create a separate issue?

**Comment by kenirwin** [comment]
@tuckerk3 - Yes -- please create a separate issue -- that will require similar but different approach. 
We don't have an RPC logo do we... Do you have any desire to mock one up?

**Comment by tuckerk3** [comment]
@kenirwin Hi Ken, sure I will put together a mock up.
