### ISSUE TITLE
Enable keyboard navigation to the events on the Event Schedule page

### ISSUE THREAD

**Issue by maxfieldk29** [alaoweb/2021.alaoweb.org#62]
Currently it is not possible to navigate to the actual event popups on the Event Schedule page without using a mouse. "Tabbing" your way through the website skips from the "Switch to Session Search" button to the footer of the website.

**Comment by kenirwin** [comment]
Possible solution: 
* make it selectable using tabindex=0
* add css/js to apply the "hover" effects on focus
* add js to activate the respective modal on keydown
