### ISSUE TITLE
Research & Publications Committee session sponsor 

### ISSUE THREAD

**Issue by tuckerk3** [alaoweb/2021.alaoweb.org#87]
RPC will sponsor the poster session ""Teaching to the Same Audience: Collaboration between Instruction and Special Collections Teams". Need to create connection; per Ken, this will be similar to process created for OLSSI sponsored session.

**Comment by kenirwin** [comment]
@tuckerk3 -- it will be easier to do this one once you've created the poster sessions

(sorry - accidentally created a duplicate issue, which is now deleted)
