### ISSUE TITLE
Update Service Project info

### ISSUE THREAD

**Issue by kenirwin** [alaoweb/2021.alaoweb.org#96]
The service project info is described in the _config.yml file in the main directory. The serviceprojectImage file should go in the /img/sponsors directory. 
Note: changes to the _config file require a jekyll-rebuild, so once you make the changes on your local machine, run `bundle exec jekyll build` and `bundle exec jekyll serve` before viewing the changes.

**Comment by kenirwin** [comment]
@tuckerk3 - are you the main contact for this year's service project? should we assign this one to you?

**Comment by tuckerk3** [comment]
@kenirwin Yes, Marsha Miles and I are coordinating, so you can assign this one to me.

**Comment by kenirwin** [comment]
Closed by #114
